Repository teamcubation/byma-back-emisores, pull requests merged in 2024-12, with the labels that each got.

#17 integro especies a emisores, falta test y global advice
  .idea/misc.xml
  src/main/java/com/byma/emisor/application/exception/especie/AtributosNulosException.java
  src/main/java/com/byma/emisor/application/exception/especie/EspecieConIdExistenteException.java
  src/main/java/com/byma/emisor/application/exception/especie/EspecieNoEncontradaException.java
  src/main/java/com/byma/emisor/application/exception/especie/ObjetoEnviadoNuloException.java
  src/main/java/com/byma/emisor/application/port/in/EspecieInPort.java
  src/main/java/com/byma/emisor/application/port/out/EspecieOutPort.java
  src/main/java/com/byma/emisor/application/service/EspecieService.java
  src/main/java/com/byma/emisor/config/WebConfig.java
  src/main/java/com/byma/emisor/domain/model/Especie.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/controller/impl/EspecieController.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/request/EspecieRequestDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/response/EspecieResponseDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/mapper/EspecieControllerMapper.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/swagger/ApiEmisor.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/swagger/ApiEspecie.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/swagger/SwaggerConfig.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/EspecieOutAdapter.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/EspecieEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/mapper/EspecieMapper.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/repository/EspecieRepository.java
  src/main/java/com/byma/emisor/util/.gitkeep
  src/main/java/com/byma/emisor/util/validation/Validador.java
  src/main/resources/application.properties
  target/classes/application.properties
Labels: Review effort [1-5]: 4

#19 Feature/integracion cruds
  .idea/dataSources.xml
  Emisores.postman_collection.json
  Fondos BYMA UP.postman_collection.json
  src/main/java/com/byma/emisor/application/exception/acdi/AcdiNoEncontradoException.java
  src/main/java/com/byma/emisor/application/exception/gerente/GerenteDuplicadoException.java
  src/main/java/com/byma/emisor/application/exception/gerente/GerenteNoEncontradoException.java
  src/main/java/com/byma/emisor/application/port/in/AcdiInPort.java
  src/main/java/com/byma/emisor/application/port/in/GerenteInPort.java
  src/main/java/com/byma/emisor/application/port/out/AcdiOutPort.java
  src/main/java/com/byma/emisor/application/port/out/GerenteOutPort.java
  src/main/java/com/byma/emisor/application/service/AcdiService.java
  src/main/java/com/byma/emisor/application/service/GerenteService.java
  src/main/java/com/byma/emisor/domain/model/Acdi.java
  src/main/java/com/byma/emisor/domain/model/EstadoAcdi.java
  src/main/java/com/byma/emisor/domain/model/Gerente.java
  src/main/java/com/byma/emisor/exception_handler/ErrorMessageResponse.java
  src/main/java/com/byma/emisor/exception_handler/ErrorMessages.java
  src/main/java/com/byma/emisor/exception_handler/GlobalExceptionHandler.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/controller/impl/AcdiController.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/controller/impl/GerenteController.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/request/ActualizarAcdiRequest.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/request/CrearAcdiRequest.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/request/GerenteRequestDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/request/GerenteUpdateRequestDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/response/AcdiResponseDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/response/EspecieResponseDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/response/GerenteResponseDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/mapper/AcdiControllerMapper.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/mapper/GerenteControllerMapper.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/swagger/ApiAcdi.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/swagger/ApiGerente.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/AcdiOutAdapter.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/GerenteOutAdapter.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/AcdiEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/EspecieEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/GerenteEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/mapper/AcdiPersistanceMapper.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/mapper/GerenteMapper.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/repository/AcdiRepository.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/repository/GerenteRepository.java
  src/main/java/com/byma/emisor/util/validation/Validador.java
  src/test/java/com/byma/emisor/adapter/AcdiOutAdapterTest.java
  src/test/java/com/byma/emisor/application/service/AcdiServiceTest.java
  src/test/java/com/byma/emisor/application/service/GerenteServiceTest.java
  src/test/java/com/byma/emisor/infrastructure/adapter/in/web/controller/impl/AcdiControllerTest.java
  src/test/java/com/byma/emisor/infrastructure/adapter/in/web/controller/impl/GerenteControllerTest.java
  src/test/java/com/byma/emisor/infrastructure/adapter/out/persistance/GerenteOutAdapterTest.java
Labels: Review effort [1-5]: 4

#21 Fixes develop
  .idea/misc.xml
  Fondos BYMA UP.postman_collection.json
  src/main/java/com/byma/emisor/application/exception/ObjetoNuloException.java
  src/main/java/com/byma/emisor/application/service/BilleteraService.java
  src/main/java/com/byma/emisor/exception_handler/GlobalExceptionHandler.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/mapper/BilleteraPersistanceMapper.java
  src/test/java/com/byma/emisor/application/service/AcdiServiceTest.java
  src/test/java/com/byma/emisor/application/service/GerenteServiceTest.java
  src/test/java/com/byma/emisor/infrastructure/adapter/in/web/controller/impl/GerenteControllerTest.java
  src/test/java/com/byma/emisor/infrastructure/adapter/out/persistance/GerenteOutAdapterTest.java
Labels: Review effort [1-5]: 4

#22 Fixes develop
  src/main/java/com/byma/emisor/application/port/out/BilleteraOutPort.java
  src/main/java/com/byma/emisor/application/service/BilleteraService.java
  src/main/java/com/byma/emisor/domain/model/Billetera.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/controller/impl/BilleteraController.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/request/BilleteraRequestDto.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/response/BilleteraResponseDto.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/swagger/ApiBilletera.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/BilleteraPersistanceAdapter.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/BilleteraEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/mapper/BilleteraPersistanceMapper.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/validation/ValidacionPersistance.java
  src/test/java/com/byma/billetera/adapter/BilleteraAdapterTest.java
  src/test/java/com/byma/billetera/controller/BilleteraControllerTest.java
  src/test/java/com/byma/billetera/service/BilleteraServiceTest.java
Labels: Review effort [1-5]: 3

#23 se resuelve fix de cors porque gustavo uso patch y no sabiamos
  src/main/java/com/byma/emisor/config/WebConfig.java
Labels: Review effort [1-5]: 2

#28 Se elimina el atributo idOrganizacion de Acdi y se agrega codigoDeAcdi
  src/main/java/com/byma/emisor/domain/model/Acdi.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/request/CrearAcdiRequest.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/response/AcdiResponseDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/mapper/AcdiControllerMapper.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/AcdiEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/mapper/AcdiPersistanceMapper.java
  src/test/java/com/byma/emisor/adapter/AcdiOutAdapterTest.java
  src/test/java/com/byma/emisor/application/service/AcdiServiceTest.java
  src/test/java/com/byma/emisor/infrastructure/adapter/in/web/controller/impl/AcdiControllerTest.java
Labels: Review effort [1-5]: 4

#26 se agrega precio a suscripcion y logica para calcularlo
  src/main/java/com/byma/emisor/application/exception/CuotaParteEsCeroException.java
  src/main/java/com/byma/emisor/application/service/SuscripcionService.java
  src/main/java/com/byma/emisor/application/validation/ValidacionSuscripcion.java
  src/main/java/com/byma/emisor/domain/model/SuscripcionModel.java
  src/main/java/com/byma/emisor/exception_handler/GlobalExceptionHandler.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/response/SuscripcionResponseDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/mapper/SuscripcionControllerMapper.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/SuscripcionEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/mapper/SuscripcionPersistenceMapper.java
  src/main/resources/app_configmap_desa.env
  src/main/resources/app_secret_desa.env
  target/classes/app_configmap_desa.env
  target/classes/app_secret_desa.env
  target/emisor-0.0.1-SNAPSHOT.jar.original
  target/maven-archiver/pom.properties
  target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
Labels: Review effort [1-5]: 4

#29 Feature/integrar acdi suscripcion
  src/main/java/com/byma/emisor/domain/model/Acdi.java
  src/main/java/com/byma/emisor/domain/model/SuscripcionModel.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/request/CrearAcdiRequest.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/request/SuscripcionRequestDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/response/AcdiResponseDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/response/SuscripcionResponseDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/mapper/AcdiControllerMapper.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/mapper/SuscripcionControllerMapper.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/AcdiEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/SuscripcionEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/mapper/AcdiPersistanceMapper.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/mapper/SuscripcionPersistenceMapper.java
  src/test/java/com/byma/emisor/adapter/AcdiOutAdapterTest.java
  src/test/java/com/byma/emisor/application/service/AcdiServiceTest.java
  src/test/java/com/byma/emisor/infrastructure/adapter/in/web/controller/impl/AcdiControllerTest.java
Labels: Review effort [1-5]: 3

#30 Archivos deploy
  Dockerfile
  resources/app_configmap_desa.env
  resources/app_secret_desa.env
  src/main/resources/app_secret_desa.env
Labels: Review effort [1-5]: 4

#31 update develop
  .gitignore
  Dockerfile
  README.md
  src/main/java/com/byma/emisor/domain/model/SuscripcionModel.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/request/SuscripcionRequestDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/response/SuscripcionResponseDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/mapper/SuscripcionControllerMapper.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/SuscripcionEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/mapper/SuscripcionPersistenceMapper.java
Labels: Review effort [1-5]: 2

#27 idBilletera permite null y data.sql
  src/main/java/com/byma/emisor/domain/model/SuscripcionModel.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/request/SuscripcionRequestDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/in/web/dto/response/SuscripcionResponseDTO.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/AcdiEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/BilleteraEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/EmisorEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/EspecieEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/GerenteEntity.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/SuscripcionEntity.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  target/classes/application.properties
  target/classes/data.sql
Labels: Review effort [1-5]: 4

#25 Feature/integracion oracle
  .env
  .gitignore
  Fondos BYMA UP.postman_collection.json
  pom.xml
  src/main/java/com/byma/emisor/EmisorApplication.java
  src/main/java/com/byma/emisor/infrastructure/adapter/out/persistance/entity/AcdiEntity.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/data.sql example
  target/classes/application.properties
  target/classes/data.sql
Labels: Review effort [1-5]: 2
